name: Typecheck

on:
    pull_request:

jobs:
    typecheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v4
            - name: Set-up Node 24.x
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: pnpm
            - name: Install
              run: pnpm install --frozen-lockfile
            - name: Typecheck
              run: pnpm typecheck
